# TODO: Update for production

availableSecrets:
  secretManager:
    - versionName: projects/${PROJECT_NUMBER}/secrets/DATABASE_URL/versions/latest
      env: "DATABASE_URL"
    - versionName: projects/${PROJECT_NUMBER}/secrets/DATABASE_URL_READONLY/versions/latest
      env: "DATABASE_URL_READONLY"
    - versionName: projects/${PROJECT_NUMBER}/secrets/OPENAI_API_KEY/versions/latest
      env: "OPENAI_API_KEY"

steps:
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    secretEnv: ["DATABASE_URL", "DATABASE_URL_READONLY", "OPENAI_API_KEY"]
    args:
      - run
      - deploy
      - redocean-backend
      - --project=${_PROJECT_ID}
      - --region=us-central1
      - --source=.
      - --platform=managed
      - --no-allow-unauthenticated
      - --port=8080
      - --set-env-vars=NODE_ENV=production
      - --set-secrets=DATABASE_URL=DATABASE_URL:latest,DATABASE_URL_READONLY=DATABASE_URL_READONLY:latest,OPENAI_API_KEY=OPENAI_API_KEY:latest

substitutions:
  _PROJECT_ID: "redocean-e9f04"
