# TODO: Update for production

steps:
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - run
      - deploy
      - redocean-backend
      - --project=${_PROJECT_ID}
      - --region=us-central1
      - --source=.
      - --platform=managed
      - --no-allow-unauthenticated
      - --port=8080
      - --set-env-vars=NODE_ENV=production,DATABASE_URL=${_DATABASE_URL},OPENAI_API_KEY=projects/${PROJECT_ID}/secrets/OPENAI_API_KEY:latest

substitutions:
  _DATABASE_URL: "replace-with-database-url"
  _PROJECT_ID: "redocean-e9f04"
