# TODO: Update for production

steps:
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "redocean-frontend"
      - "--project"
      - "redocean-e9f04"
      - "--region"
      - "us-central1"
      - "--source"
      - "."
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
      - "--port"
      - "8080"
      - "--set-env-vars"
      - "NODE_ENV=production"
      - "BACKEND_URL=https://redocean-backend-989102844665.us-central1.run.app"
